/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.web.arproject.uas.view;

import id.web.arproject.uas.controller.LaporanKeluarController;
import id.web.arproject.uas.controller.LaporanMasukController;
import id.web.arproject.uas.controller.PelangganController;
import id.web.arproject.uas.controller.PerusahaanController;
import id.web.arproject.uas.controller.SampahController;
import id.web.arproject.uas.controller.TrxBeliController;
import id.web.arproject.uas.controller.TrxJualController;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Mea
 */
public class HomeView extends javax.swing.JFrame {
    
    private final static LoginView loginView = new LoginView();

    private final PelangganController pelangganController = new PelangganController();
    private final SampahController sampahController = new SampahController();
    private final PerusahaanController perusahaanController = new PerusahaanController();
    
    private final TrxBeliController trxBeliController = new TrxBeliController();
    private final TrxJualController trxJualController = new TrxJualController();
    
    private final LaporanMasukController laporanMasukController = new LaporanMasukController();
    private final LaporanKeluarController laporanKeluarController = new LaporanKeluarController();
    
    private AboutView aboutView;

    /**
     * Creates new form viewHome
     */
    public HomeView() {
        initComponents();
        
        setUkuranLokasiFrame(0.8, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemFTentang = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemFLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemMDPelanggan = new javax.swing.JMenuItem();
        menuItemMDSampah = new javax.swing.JMenuItem();
        menuItemMDPerusahaan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemTBeli = new javax.swing.JMenuItem();
        menuItemTJual = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemLBeli = new javax.swing.JMenuItem();
        menuItemLJual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);

        javax.swing.GroupLayout mdiDesktopPaneLayout = new javax.swing.GroupLayout(mdiDesktopPane);
        mdiDesktopPane.setLayout(mdiDesktopPaneLayout);
        mdiDesktopPaneLayout.setHorizontalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        mdiDesktopPaneLayout.setVerticalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        menuItemFTentang.setText("Tentang Kelompok");
        menuItemFTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFTentangActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemFTentang);
        jMenu1.add(jSeparator1);

        menuItemFLogout.setText("Logout");
        menuItemFLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemFLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");

        menuItemMDPelanggan.setText("Pelanggan");
        menuItemMDPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMDPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemMDPelanggan);

        menuItemMDSampah.setText("Sampah");
        menuItemMDSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMDSampahActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemMDSampah);

        menuItemMDPerusahaan.setText("Perusahaan");
        menuItemMDPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMDPerusahaanActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemMDPerusahaan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        menuItemTBeli.setText("Transaksi Beli");
        menuItemTBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTBeliActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemTBeli);

        menuItemTJual.setText("Transaksi Jual");
        menuItemTJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTJualActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemTJual);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");

        menuItemLBeli.setText("Transaksi Beli");
        menuItemLBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLBeliActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemLBeli);

        menuItemLJual.setText("Transaksi Jual");
        menuItemLJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLJualActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemLJual);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setUkuranLokasiFrame(double skala, boolean tengah){
        Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
        setSize((int)(skala * dimensi.getWidth()),(int)(skala * dimensi.getHeight()));
        
        if (tengah){
            setLocation((int)((dimensi.getWidth() - getWidth())/2), (int)((dimensi.getHeight() - getHeight())/2));
        }
    } 

    private void menuItemFLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFLogoutActionPerformed
        // TODO add your handling code here:
        System.out.println("Aksi Logout");
        this.setVisible(false);
        loginView.setVisible(true);
    }//GEN-LAST:event_menuItemFLogoutActionPerformed

    private void menuItemMDPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMDPelangganActionPerformed
        // TODO add your handling code here:
        System.out.println("Buka: MDPelangganView");
        pelangganController.openMasterData(mdiDesktopPane);
    }//GEN-LAST:event_menuItemMDPelangganActionPerformed

    private void menuItemMDSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMDSampahActionPerformed
        // TODO add your handling code here:
        System.out.println("Buka: MDSampahView");
        sampahController.openMasterData(mdiDesktopPane);
    }//GEN-LAST:event_menuItemMDSampahActionPerformed

    private void menuItemMDPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMDPerusahaanActionPerformed
        // TODO add your handling code here:
        System.out.println("Buka: MDPerusahaanView");
        perusahaanController.openMasterData(mdiDesktopPane);
    }//GEN-LAST:event_menuItemMDPerusahaanActionPerformed

    private void menuItemTBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTBeliActionPerformed
        // TODO add your handling code here:
        System.out.println("Buka: TrxBeliView");
        trxBeliController.openTransaksi(mdiDesktopPane);
    }//GEN-LAST:event_menuItemTBeliActionPerformed

    private void menuItemTJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTJualActionPerformed
        // TODO add your handling code here:
        System.out.println("Buka: TrxJualView");
        trxJualController.openTransaksi(mdiDesktopPane);
    }//GEN-LAST:event_menuItemTJualActionPerformed

    private void menuItemLBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLBeliActionPerformed
        // TODO add your handling code here:
        System.out.println("Buka: LaporanMasukView");
        laporanMasukController.openLaporan(mdiDesktopPane);
    }//GEN-LAST:event_menuItemLBeliActionPerformed

    private void menuItemLJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLJualActionPerformed
        // TODO add your handling code here:
        System.out.println("Buka: LaporanKeluarView");
        laporanKeluarController.openLaporan(mdiDesktopPane);
    }//GEN-LAST:event_menuItemLJualActionPerformed

    private void menuItemFTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFTentangActionPerformed
        // TODO add your handling code here:
        aboutView = new AboutView(null, true);
        Frame frame = JOptionPane.getFrameForComponent(mdiDesktopPane);
        aboutView.setTitle("Tentang Kelompok");
        aboutView.setLocationRelativeTo(frame);
        aboutView.setVisible(true);
    }//GEN-LAST:event_menuItemFTentangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane mdiDesktopPane;
    private javax.swing.JMenuItem menuItemFLogout;
    private javax.swing.JMenuItem menuItemFTentang;
    private javax.swing.JMenuItem menuItemLBeli;
    private javax.swing.JMenuItem menuItemLJual;
    private javax.swing.JMenuItem menuItemMDPelanggan;
    private javax.swing.JMenuItem menuItemMDPerusahaan;
    private javax.swing.JMenuItem menuItemMDSampah;
    private javax.swing.JMenuItem menuItemTBeli;
    private javax.swing.JMenuItem menuItemTJual;
    // End of variables declaration//GEN-END:variables
}
