/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.web.arproject.uas.view;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import id.web.arproject.uas.controller.PerusahaanController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mea
 */
public class MDPerusahaanView extends javax.swing.JInternalFrame {
    
    private final dialogMessage dialogMessage = new dialogMessage();
    public DefaultTableModel perusahaanTableModel;
    public final PerusahaanController perusahaanController = new PerusahaanController();

    /**
     * Creates new form MDPerusahaanView
     */
    public MDPerusahaanView() {
        initComponents();
        
        perusahaanTableModel = (DefaultTableModel) mainTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAksiTambah = new javax.swing.JButton();
        btnAksiTutup = new javax.swing.JButton();
        btnAksiHapus = new javax.swing.JButton();
        btnAksiEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();

        setTitle("Master Data Perusahaan");

        btnAksiTambah.setText("Tambah");
        btnAksiTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiTambahActionPerformed(evt);
            }
        });

        btnAksiTutup.setText("Tutup");
        btnAksiTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiTutupActionPerformed(evt);
            }
        });

        btnAksiHapus.setText("Hapus");
        btnAksiHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiHapusActionPerformed(evt);
            }
        });

        btnAksiEdit.setText("Edit");
        btnAksiEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAksiTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAksiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAksiHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAksiTutup)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAksiTambah)
                    .addComponent(btnAksiTutup)
                    .addComponent(btnAksiHapus)
                    .addComponent(btnAksiEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Perusahaan", "No Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mainTable);
        if (mainTable.getColumnModel().getColumnCount() > 0) {
            mainTable.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getRefreshList() {
        perusahaanController.refreshListDirect(this);
    }
    
    public void tampilkanData(Object[][] list) {
        perusahaanTableModel.setRowCount(0);
        if ((list != null) && (list.length > 0)) {
            for (Object[] list1 : list) {
                perusahaanTableModel.addRow(list1);
            }
        }
    }

    private void btnAksiTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiTambahActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Aksi: MDPelangganView | Tambah");
        
        perusahaanController.openTambahData().addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println("Aksi: MDPelangganView | openTambahData | windowClosed | getRefreshList");
                getRefreshList();
            }
        });
    }//GEN-LAST:event_btnAksiTambahActionPerformed

    private void btnAksiEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiEditActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Aksi: MDPelangganView | Edit");
        if (mainTable.getSelectedRowCount() > 0) {
            if (mainTable.getSelectedRowCount() == 1) {
                String getNamaCustumer = mainTable.getValueAt(mainTable.getSelectedRow(), 1).toString();
                perusahaanController.openEditData(getNamaCustumer).addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e) {
                        System.out.println("Aksi: MDPelangganView | openEditData | windowClosed | getRefreshList");
                        getRefreshList();
                    }
                });
            } else {
                JOptionPane.showMessageDialog(null, "Data yang di edit harus 1", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang di pilih", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAksiEditActionPerformed

    private void btnAksiHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiHapusActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Aksi: MDPelangganView | Hapus");
        if (mainTable.getSelectedRowCount() > 0) {
            if (dialogMessage.tampilkanPilihan("Apa Anda yakin ingin menghapus data ini?","Aksi", new Object[]{"Ya","Tidak"}) == 0) {
                ArrayList<String> tasks = new ArrayList<>();
                int[] selectedRows = mainTable.getSelectedRows();
                for (int i = 0; i < selectedRows.length; i++) {
                    String taskAsArray = (String) (mainTable.getValueAt(mainTable.convertRowIndexToModel(selectedRows[i]), 1));
                    tasks.add(taskAsArray);
                }
                
                Gson gson = new GsonBuilder().serializeSpecialFloatingPointValues().serializeNulls().create();
                System.out.println(gson.toJson(tasks));
                
                perusahaanController.delete(tasks);
                getRefreshList();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang di pilih", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAksiHapusActionPerformed

    private void btnAksiTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiTutupActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Aksi: MDPelangganView | Tutup");
        this.dispose();
    }//GEN-LAST:event_btnAksiTutupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAksiEdit;
    private javax.swing.JButton btnAksiHapus;
    private javax.swing.JButton btnAksiTambah;
    private javax.swing.JButton btnAksiTutup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables
}
