/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.web.arproject.uas.view;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import id.web.arproject.uas.controller.TrxBeliController;
import java.awt.Dialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mea
 */
public class TrxBeliView extends javax.swing.JInternalFrame {
    private final TrxBeliController trxBeliController = new TrxBeliController();
    private final dialogMessage dialogMessage = new dialogMessage();
    
    private final DefaultTableModel mainTableModel;
    private int currentData = 0;
    private float currentHarga = 0;
    private int currentBerat = 0;

    /**
     * Creates new form TrxBeli
     */
    public TrxBeliView() {
        initComponents();
        
        mainTableModel = (DefaultTableModel) mainTable.getModel();
        
        inputBerat.setText("0");
        inputHarga.setText("Rp0,00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        btnAksiLihat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputBerat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputHarga = new javax.swing.JTextField();
        btnAksiSimpan = new javax.swing.JButton();
        btnAksiBatal = new javax.swing.JButton();
        btnAksiTambah = new javax.swing.JButton();
        btnAksiHapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();

        setTitle("Transaksi Beli Sampah");

        jLabel1.setText("Nama Pelanggan");

        inputNama.setEditable(false);

        btnAksiLihat.setText("Lihat");
        btnAksiLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiLihatActionPerformed(evt);
            }
        });

        jLabel2.setText("Berat Sampah");

        inputBerat.setEditable(false);

        jLabel3.setText("Total Harga Beli");

        inputHarga.setEditable(false);

        btnAksiSimpan.setText("Simpan");
        btnAksiSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiSimpanActionPerformed(evt);
            }
        });

        btnAksiBatal.setText("Batal");
        btnAksiBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiBatalActionPerformed(evt);
            }
        });

        btnAksiTambah.setText("Tambah Sampah");
        btnAksiTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiTambahActionPerformed(evt);
            }
        });

        btnAksiHapus.setText("Hapus");
        btnAksiHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAksiHapusActionPerformed(evt);
            }
        });

        jLabel4.setText("Kg");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputBerat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputHarga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAksiLihat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAksiHapus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAksiBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAksiSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAksiTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAksiLihat)
                    .addComponent(btnAksiSimpan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAksiBatal)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAksiTambah)
                    .addComponent(btnAksiHapus))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Sampah", "Harga Beli / Kg", "Berat Sampah (Kg)", "Harga Beli"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(mainTable);
        if (mainTable.getColumnModel().getColumnCount() > 0) {
            mainTable.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void resetData() {
        inputNama.setText("");
        inputBerat.setText("");
        inputHarga.setText("");
        
        mainTableModel.setRowCount(0);
    }

    private void btnAksiLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiLihatActionPerformed
        // TODO add your handling code here:
        Dialog selectDataPelangganView = trxBeliController.openPelangganDialog();
        selectDataPelangganView.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println("Aksi: TrxBeliView | btnAksiLihatActionPerformed | windowClosed | afterDialogPelanggan");
                afterDialogPelanggan();
            }
        });
    }//GEN-LAST:event_btnAksiLihatActionPerformed

    private void afterDialogPelanggan() {
        inputNama.setText(trxBeliController.getSelectedData());
    }
    
    private void btnAksiBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiBatalActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btnAksiBatalActionPerformed

    private void btnAksiSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiSimpanActionPerformed
        // TODO add your handling code here:
        
        if (mainTable.getRowCount() > 0) {
            if (dialogMessage.tampilkanPilihan("Apa Anda yakin ingin menyimpan data ini?","Aksi", new Object[]{"Ya","Tidak"}) == 0) {
                ArrayList<ArrayList> dataSampah = new ArrayList<>();
                int selectedRows = mainTable.getRowCount();
                for (int i = 0; i < selectedRows; i++) {
                    float getDataSatuan = Float.parseFloat(mainTable.getValueAt(mainTable.convertRowIndexToModel(i), 2).toString().replace("Rp","").replace(".","").replace(",","."));
                    int getDataBerat = Integer.parseInt(mainTable.getValueAt(mainTable.convertRowIndexToModel(i), 3).toString());
                    String getNamaSampah = mainTable.getValueAt(mainTable.convertRowIndexToModel(i), 1).toString();
                    float getDataEstimasi = getDataSatuan * getDataBerat;
                    ArrayList dataArray = new ArrayList<>();
                    dataArray.add(getNamaSampah);
                    dataArray.add(getDataSatuan);
                    dataArray.add(getDataBerat);
                    dataArray.add(getDataEstimasi);
                    dataSampah.add(dataArray);
                }
                
                Gson gson = new GsonBuilder().serializeSpecialFloatingPointValues().serializeNulls().create();
                System.out.println(gson.toJson(dataSampah));
                
                trxBeliController.simpan(this, inputNama, inputBerat, inputHarga, dataSampah);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang di pilih", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAksiSimpanActionPerformed

    private void btnAksiTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiTambahActionPerformed
        // TODO add your handling code here:
        
        trxBeliController.openSampahDialog().addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println("Aksi: TrxBeliView | btnAksiTambahActionPerformed | windowClosed | afterDialogSampah");
                afterDialogSampah();
            }
        });
    }//GEN-LAST:event_btnAksiTambahActionPerformed

    private void afterDialogSampah() {
        if (trxBeliController.getSampahModel().baca(trxBeliController.getSelectedData())) {
            currentData++;
            float getDataSatuan = trxBeliController.getSampahModel().getHarga_satuan();
            int getDataBerat = trxBeliController.getDataBerat();
            
            float getDataEstimasi = getDataSatuan * getDataBerat;
            
            currentHarga += getDataEstimasi;
            currentBerat += getDataBerat;
            
            inputBerat.setText(Integer.toString(currentBerat));
            inputHarga.setText(NumberFormat.getCurrencyInstance(new Locale("id", "ID")).format(currentHarga));

            mainTableModel.addRow(new Object[]{currentData, trxBeliController.getSampahModel().getNama_sampah(), NumberFormat.getCurrencyInstance(new Locale("id", "ID")).format(getDataSatuan), getDataBerat, NumberFormat.getCurrencyInstance(new Locale("id", "ID")).format(getDataEstimasi)});
        }
    }
    
    private void btnAksiHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAksiHapusActionPerformed
        // TODO add your handling code here:
        
        if (mainTable.getSelectedRowCount() > 0) {
            if (mainTable.getSelectedRowCount() == 1) {
                float getDataSatuan = Float.parseFloat(mainTable.getValueAt(mainTable.getSelectedRow(), 2).toString().replace("Rp","").replace(".","").replace(",","."));
                int getDataBerat = Integer.parseInt(mainTable.getValueAt(mainTable.getSelectedRow(), 3).toString());

                float getDataEstimasi = getDataSatuan * getDataBerat;
                
                currentHarga -= getDataEstimasi;
                currentBerat -= getDataBerat;

                inputBerat.setText(Integer.toString(currentBerat));
                inputHarga.setText(NumberFormat.getCurrencyInstance(new Locale("id", "ID")).format(currentHarga));
                mainTableModel.removeRow(mainTable.getSelectedRow());
                
                currentData--;
            } else {
                JOptionPane.showMessageDialog(null, "Data yang di pilih hanya 1", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang di pilih", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAksiHapusActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAksiBatal;
    private javax.swing.JButton btnAksiHapus;
    private javax.swing.JButton btnAksiLihat;
    private javax.swing.JButton btnAksiSimpan;
    private javax.swing.JButton btnAksiTambah;
    private javax.swing.JTextField inputBerat;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables
}
